### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gericho**
please revise the code, I don't understand the sleep_state

### CODE REVIEW

**Comment by claytonjn** [comment]
Did you find the [Advanced Configuration](https://github.com/claytonjn/hass-circadian_lighting/wiki/Advanced-Configuration) section in the wiki?

**Comment by gericho** [comment]
Yes and thank you, I was able to figure out 
how to use the commands, I’m proposing to add some of them in the example fit the understanding of everyone

**Comment by claytonjn** [comment]
I'll have to think about it, I specifically have the readme examples as the minimum required configuration so as not to confuse new users. Maybe I should add examples to the Advanced Configuration WiKi instead.

**Comment by gericho** [comment]
Yes maybe better, thank you very much. Really appreciated

**Pull request closed without merging**
