### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by robertomano24**
fix breaking change with astral

### CODE REVIEW

**Comment by obi11235** [comment]
These changes worked for me, Hope we can get them merged.

**Comment by BenoitAnastay** [comment]
I think, we must integrate a fallback for retrocompatibility before merging 

Something like 
```python
try:
            import astral.location as astralLocation       
except ImportError:
            location = astral.Location()
else:
            location = astralLocation.Location() 
/.../
```

**Comment by michaelkuty** [comment]
:+1:

**Comment by robertomano24** [comment]
Here is a fork that works: https://github.com/robertomano24/circadian_lighting
I will do my best to keep this fork updated to work with HA. It should be working now. You will need to add the files to your custom_components folder manually.

If you use Hue and want the Hue scenes you make to update with CL values for a seamless integration, check out my repo here: https://github.com/robertomano24/circadian_lighting-hue

**Comment by claytonjn** [comment]
PR #138 already existed to fix this change; I have merged that into the dev (beta) branch and am testing now. Once I verified that astral v2 works I'll close this PR. 

Thank you for contributing to the development and I'm sorry it took so long to review this.

**Comment by claytonjn** [comment]
Got a handful of people confirming that 2.0.4 is working properly and no complaints about compatibility with HA Core 2015.5.x so I'm going to close this PR. Thanks everyone!

**Pull request closed without merging**
