### PR TITLE
Update SwitchDevice to SwitchEntity

### PR DESCRIPTION
**Pull request by LEJOUI**
In HA 0.110 SwitchDevice is going to be deprecated and is going to be renamed to SwitchEntity.

image

https://github.com/home-assistant/core/pull/34673

I think this change will solve it. Could you review it? Then we could merge it when HA 0.110 is out of beta and stable. Not sure how this would effect the component on older HA instances though.

### CODE REVIEW

**Comment by claytonjn** [comment]
I don't have a dev environment set up on the beta branch right now unfortunately but this looks right based on the PR you linked. Maybe for backwards compatibility the import could be wrapped in a try and `SwitchDevice as SwitchEntity` could be imported if there's an exception with SwitchEntity

**Comment by basnijholt** [comment]
Let's do this!

HA 0.110 is out where this is needed.

**Comment by LEJOUI** [comment]
Not an expert with this, will this work?

**Comment by basnijholt** [comment]
I actually looked at the code. This won't work.

**Comment by K-Money** [comment]
I came across this post explaining the change.
https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/

**Comment by LEJOUI** [comment]
Thanks!

**Comment by LEJOUI** [comment]
@claytonjn could you review when you have the time?

**Comment by basnijholt** [comment]
Please merge, this works :tada:

**Comment by claytonjn** [comment]
Sorry for the delay...Things are starting to open up here in Michigan and I've been working 14+ hour days. Didn't have a chance to test but it conforms to the documented solution and I'll trust that it works. Pushed to beta branch for now and I'll merge into master in a couple days if there are no reported issues.

**Comment by claytonjn** [comment]
Merged into master a couple days ago, should be available in HACS.

**Pull request merged**
