### PR TITLE
Feature: support Astral v2

### PR DESCRIPTION
**Pull request by dn0sar**
Support for the new API in Astral v2.2. Without this pull request the component will not load on Home Assistant 2021.5.0.

### CODE REVIEW

**Comment by dn0sar** [comment]
@ChopperRob thanks for pointing that out, I also just noticed that the brightness was not changing on my setup. Should work properly with the last commit in the PR. Can you try it?

**Comment by glowery** [comment]
@dn0sar thanks for the work, made the changes to the two files and all works like a charm!

**Comment by ChopperRob** [comment]
I just installed the new version and it is now starting without errors. I will monitor it the next few days.

**Comment by pvmil** [comment]
It would be nice if this gets merged, cannot upgrade to new HA 2012.5 now (I do not know how to make these changes myself, an update through hacs would be a lot simpler.. :)

**Comment by dn0sar** [comment]
> I prefer the backwards-compatible approach implemented

Makes sense.

> Thank you for helping with the development of this component, I'm sorry it took so long for me to be able to review.

No worries, thanks for answering anyway and for maintaining the project, it's been really useful so far :)

**Comment by claytonjn** [comment]
@dn0sar I pushed 2.0.4-beta with fixes for Astral v2 and HA Core 2021.5.x, if you get a chance to try it please let me know if anything's not working for you!

**Comment by dn0sar** [comment]
@claytonjn Seem to be working fine on my system for now. I'll open an issue if I notice anything weird in the following days

**Pull request closed without merging**
